---
version: "3.9"
services:
  web:
    build: ./
    image: rentacar:v1
    container_name: web
    ports:
      - "9000:9000"
    working_dir: /app
    volumes:
      - ".:/app"
      - "node_modules:/app/node_modules"
    command: sh docker-entrypoint.sh
    environment:
      - NODE_ENV="production"
      - DB_HOST=${DB_HOST}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:5.7
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./db/db.sql:/docker-entrypoint-initdb.d/db.sql"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped

volumes:
  node_modules:
